.TH 2bwm "1" "2BWMDATE" "1.0" ""
.SH NAME
2bwm
.SH DESCRIPTION
A fast floating Window Manager using XCB, controlled by keyboard with complementary mouse usage.
.SH OPTIONS
.TP
.I "Start a new terminal window"
MOD + Enter
.TP
.I "Move focuswindow to [vertical-top] [vertical-center] [vertical-buttom] [top-left] [buttom-right] of screen"
MOD + [u][y][b][g][n]
.TP
.I "[Focus next window list] [ocus next window in the same list]"
[MOD + Tab] [MOD + Control + Tab]
.TP
.I "[Select window] [Select All window from current workspace]"
[MOD + o] [MOD + Shfit + o]
.TP
.I "Resize window to A4[A5][A3][A8] papper size"
MOD + [4][5][3][8]
.TP
.I "Move window step by step [up][down][right][left]"
MOD + [k][j][l][h]
.TP
.I "Move windows side by side."
MOD + s
.TP
.I "Increase/Decrease window while keeping aspect."
[MOD + r] [MOD + Shift + r]
.TP
.I "[Change focus to workspace Number] [Move focus-window to Workspace Number]"
[MOD + Number] [MOD + Shift + Number]
.TP
.I "[Unkillable window] [always on top window] [make window stay on all workspaces]"
[MOD + a] [MOD + t] [MOD + f]
.TP
.I "[Hide window] [Unhide window]"
[MOD + i] [MOD + Shift + i]
.TP
.I "[Delete window] [Exit 2bwm]"
[MOD + p] [MOD + Shift + p]

.SH AUTHORS
Forked from github.com/venam/2bwm
rewritten by Yang Li.  
.SH REPORTING BUGS
github.com/netcrop/2bwm
.SH LICENSE
ISC License
.br
